## 10. 결측치
비어있는 데이터

In [1]:
import pandas as pd
df=pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

## 데이터 채우기 fillna

In [2]:
df.fillna('') #NaM 데이터를 빈 칸으로 채움

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80
5번    강백호  북산고  188   15   20   10  35  10
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [3]:
df.fillna('없음') 
#column 상관 없이 비어있는 모든 칸이 '없음'으로 채워짐
#inplace=Ture를 하지 않았음으로 실제 데이테는 반영되지 않음

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80          없음
5번    강백호  북산고  188   15   20   10  35  10          없음
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [4]:
df['SW특기'].fillna('없음', inplace=True)
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80          없음
5번    강백호  북산고  188   15   20   10  35  10          없음
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

## 데이터 제외하기 dropna

In [5]:
import pandas as pd
df=pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [6]:
df.dropna() #전체 데이터 중에서 NaN을 포함하는 데이터 삭제

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

- axis: index or columns 
 - index: 해당하는 row를 지우고,
 - columns: 당하는 col을 지움
- how: any or all
 - any: 데이터 중에 하나라도 NaN이 있으면 지움
 -all: row 또는 col의 데이터가 모두 NaN이면 지움

In [7]:
df.dropna(axis='index', how='any') #NaN이 하나도 있는 row 삭제

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [8]:
df.dropna(axis='columns') #how는 any가 default, NaN이 하나라도 있는 col 삭제

       이름   학교    키   국어   영어   수학  과학  사회
지원번호
1번    채치수  북산고  197   90   85  100  95  85
2번    정대만  북산고  184   40   35   50  55  25
3번    송태섭  북산고  168   80   75   70  80  75
4번    서태웅  북산고  187   40   60   70  75  80
5번    강백호  북산고  188   15   20   10  35  10
6번    변덕규  능남고  202   80  100   95  85  80
7번    황태산  능남고  188   55   65   45  40  35
8번    윤대협  능남고  190  100   85   90  95  95